"""Independent Hunter global decision layer.

This package may coordinate professional capabilities only through the frozen
public protocol. Professional backend implementations must remain outside it.
"""

from .capabilities import (
    DEFAULT_CAPABILITIES,
    Capability,
    CapabilityCatalog,
    CapabilityCost,
    default_catalog,
)
from .contract_ingress import (
    DecisionIngressPolicy,
    DecisionNormalizationError,
    decision_fingerprint,
    normalize_decision_json,
)
from .decisions import (
    DECISION_SCHEMA_VERSION,
    BlockedDecision,
    CompleteDecision,
    DecisionAction,
    InvokeCapabilityDecision,
    SupervisorDecision,
    VerifyDecision,
    decision_from_dict,
)
from .orchestrator import (
    AUDIT_FILENAME,
    SUBTASKS_DIRECTORY,
    BudgetLedger,
    CapabilityAdapterRegistry,
    HunterOrchestrator,
    OrchestrationLimits,
    OrchestrationResult,
    OrchestrationStatus,
    ResultInterpreter,
    SupervisorEngine,
)
from .state import (
    BRAIN_STATE_FILENAME,
    ArtifactRecord,
    DispatchRecord,
    EvidenceRecord,
    HunterWorldState,
    Hypothesis,
    UnresolvedQuestion,
    VerifiedFact,
)
from .supervisor import (
    SYSTEM_INSTRUCTIONS,
    DecisionAttemptTrace,
    DecisionModel,
    DeepSeekDecisionModel,
    DeepSeekSupervisorConfig,
    HunterSupervisor,
    ModelDecisionResult,
    SupervisionOutcome,
    SupervisorConfigurationError,
    SupervisorContextLimits,
    SupervisorDecisionRejected,
    SupervisorModelError,
    SupervisorOutputError,
)
from .state_updater import (
    QuestionResolution,
    SemanticStateProposal,
    StateDelta,
    StateUpdate,
    WorldStateUpdater,
)
from .validator import (
    BudgetSnapshot,
    DecisionValidation,
    DeterministicDecisionValidator,
    ValidationCode,
    ValidationIssue,
    ValidatorPolicy,
)
from .verifier import (
    DeterministicCheck,
    GlobalVerificationOutcome,
    GlobalVerificationStatus,
    GlobalVerifier,
    SemanticAssessment,
    SemanticVerificationModel,
    SemanticVerificationRequest,
    VerificationCode,
    VerificationIssue,
)
from .question_generator import CrossDomainQuestionGenerator

__all__ = (
    "DEFAULT_CAPABILITIES",
    "Capability",
    "CapabilityCatalog",
    "CapabilityCost",
    "DecisionIngressPolicy",
    "DecisionNormalizationError",
    "decision_fingerprint",
    "normalize_decision_json",
    "DECISION_SCHEMA_VERSION",
    "BlockedDecision",
    "CompleteDecision",
    "DecisionAction",
    "InvokeCapabilityDecision",
    "SupervisorDecision",
    "VerifyDecision",
    "decision_from_dict",
    "AUDIT_FILENAME",
    "SUBTASKS_DIRECTORY",
    "BudgetLedger",
    "CapabilityAdapterRegistry",
    "HunterOrchestrator",
    "OrchestrationLimits",
    "OrchestrationResult",
    "OrchestrationStatus",
    "ResultInterpreter",
    "SupervisorEngine",
    "BRAIN_STATE_FILENAME",
    "ArtifactRecord",
    "DispatchRecord",
    "EvidenceRecord",
    "HunterWorldState",
    "Hypothesis",
    "UnresolvedQuestion",
    "VerifiedFact",
    "SYSTEM_INSTRUCTIONS",
    "DecisionAttemptTrace",
    "DecisionModel",
    "DeepSeekDecisionModel",
    "DeepSeekSupervisorConfig",
    "HunterSupervisor",
    "ModelDecisionResult",
    "SupervisionOutcome",
    "SupervisorConfigurationError",
    "SupervisorContextLimits",
    "SupervisorDecisionRejected",
    "SupervisorModelError",
    "SupervisorOutputError",
    "QuestionResolution",
    "SemanticStateProposal",
    "StateDelta",
    "StateUpdate",
    "WorldStateUpdater",
    "BudgetSnapshot",
    "DecisionValidation",
    "DeterministicDecisionValidator",
    "ValidationCode",
    "ValidationIssue",
    "ValidatorPolicy",
    "DeterministicCheck",
    "GlobalVerificationOutcome",
    "GlobalVerificationStatus",
    "GlobalVerifier",
    "SemanticAssessment",
    "SemanticVerificationModel",
    "SemanticVerificationRequest",
    "VerificationCode",
    "VerificationIssue",
    "default_catalog",
    "CrossDomainQuestionGenerator",
)
